export const columns = [
  { name: 'id', title: 'ID' },
  { name: 'name', title: 'Name' },
  { name: 'country_code', title: 'Country code' },
  { name: 'weight', title: 'Weight(kg)' },
  { name: 'adaptability', title: 'Adaptability' },
  { name: 'energy_level', title: 'Energy level' },
  { name: 'life_span', title: 'Life Time' },
];

export const stats = [
  'hypoallergenic',
  'indoor',
  'affection_level',
  'lap',
  'adaptability',
  'child_friendly',
  'dog_friendly',
  'energy_level',
  'grooming',
  'health_issues',
  'intelligence',
  'shedding_level',
  'social_needs',
  'stranger_friendly',
  'hairless',
  'natural',
  'suppressed_tail',
  'short_legs',
];
